name: autofix.ci # needed to securely identify the workflow

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  autofix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - run: corepack enable
      - uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4
        with:
          node-version: 20.5
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Format files
        run: pnpm run lint:fix

      - name: Format Markdown files
        run: pnpm run lint:md:fix

      - uses: autofix-ci/action@2891949f3779a1cafafae1523058501de3d4e944
